---
# tasks file for roles/gnome-configuration
- name: install gnome tweaks
  dnf:
    name: gnome-tweaks
    state: latest
  become: True
- name: turn off natural scrolling
  include_tasks: natural-scrolling.yml
  loop:
  - touchpad
  - mouse

- name: configure isolated tab switching for workspaces
  dconf:
    key: /org/gnome/shell/app-switcher/current-workspace-only
    state: read
  register: result
- dconf:
    key: /org/gnome/shell/app-switcher/current-workspace-only
    value: "true"
    state: present
  when: result.value != "true"
    
