---
# tasks file for extra-installs
- name: install dev tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
  - npm
  - git

- name: docker
  dnf:
    name: docker
    state: latest
  notify: restart docker daemon

- name: add docker group
  group:
    name: docker
    state: present

- name: add {{ user_name }} to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: true

- name: install cfssl tools
  get_url:
    url: https://pkg.cfssl.org/R{{ cfssl_version }}/{{ item }}_linux-amd64
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
  - cfssl
  - cfssljson

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755