---
# tasks file for roles/extra-installations

- name: add gpg key for atom repo
  rpm_key:
    state: present
    key: https://packagecloud.io/AtomEditor/atom/gpgkey
- name: Add repository for atom
  yum_repository:
    name: atom
    description: Atom Editor
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch/
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
- name: install atom
  dnf:
    name: atom
    state: latest
